# Generated by Django 4.0.4 on 2022-05-23 16:09

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='face_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=191)),
                ('Password', models.IntegerField()),
                ('Picture', models.ImageField(blank=True, null=True, upload_to=members.models.filepath)),
            ],
            options={
                'db_table': 'members_face_pay',
            },
        ),
    ]
